First version of steam standalone. Heavily modified version of graysky2's package.

diff --git a/readme.install b/readme.install
--- a/readme.install
+++ b/readme.install
@@ -1,59 +1,30 @@
 post_install() {
-	getent group kodi > /dev/null || groupadd -g 420 kodi
-	if ! getent passwd kodi > /dev/null; then
-		useradd -c 'kodi user' -u 420 -g kodi -G audio,video,network,optical \
-			-d /var/lib/kodi -s /usr/bin/nologin kodi
-		passwd -l kodi > /dev/null
-		[[ ! -d /var/lib/kodi/.kodi ]] &&
-			mkdir /var/lib/kodi/.kodi &&
-			chown -R kodi:kodi /var/lib/kodi/.kodi
+	getent group steam > /dev/null || groupadd -g 540 steam
+	if ! getent passwd steam > /dev/null; then
+		useradd -c 'Steam user' -u 540 -g steam -G audio,video,network,optical \
+			-d /var/lib/steam -s /usr/bin/nologin steam
+		passwd -l steam > /dev/null
 	fi
 }
 
 post_upgrade() {
 	post_install $1
-	if ! getent group kodi | cut -d: -f3 | grep 420 > /dev/null 2>&1; then
-		groupmod -g 420 kodi > /dev/null 2>&1
+	if ! getent group steam | cut -d: -f3 | grep 540 > /dev/null 2>&1; then
+		groupmod -g 540 steam > /dev/null 2>&1
 	fi
-	if ! id -u kodi | grep 420 > /dev/null 2>&1; then
-		usermod -u 420 kodi > /dev/null 2>&1
+	if ! id -u steam | grep 540 > /dev/null 2>&1; then
+		usermod -u 420 steam > /dev/null 2>&1
 		if [[ $? -ne 0 ]]; then
-			echo "Changing uid of user kodi failed."
+			echo "Changing uid of user steam failed."
 			echo "It is recommended that the uid is changed."
-			echo "Stop all processes running under the kodi user and reinstall kodi"
-			echo "or change the uid manually. (usermod -u 420 kodi)"
+			echo "Stop all processes running under the steam user and reinstall steam"
+			echo "or change the uid manually. (usermod -u 420 steam)"
 		fi
-		chown -R kodi:kodi /var/lib/kodi
-	fi
-
-	if [[ -d /var/lib/xbmc ]]; then
-		echo "If you are upgrading from xbmc->kodi and wish to keep your"
-		echo "settings, simply follow these steps after the install:"
-		echo 
-		echo "cp -a /var/lib/xbmc/.xbmc/* /var/lib/kodi/.kodi"
-		echo "chown -R kodi:kodi /var/lib/kodi"
-	fi
-	
-	if [ "$(vercmp $2 1.8-1)" -lt 1 ]; then
-		if [[ -f /etc/X11/Xwrapper.config ]]; then
-			echo '-> It is no longer necessary to keep /etc/X11/Xwrapper.config for kodi to start properly.'
-		fi
-	else
-		/bin/true
+		chown -R steam:steam /var/lib/steam
 	fi
 }
 
 post_remove() {
-	getent passwd kodi > /dev/null 2>&1 && userdel kodi
-	getent group kodi > /dev/null 2>&1 && groupdel kodi
-}
-
-pre_install() {
-	/usr/bin/systemctl status xbmc.service &>/dev/null
-	if [[ $? -eq 0 ]]; then
-		# xbmc is running via this service
-		/usr/bin/systemctl stop xbmc.service &>/dev/null
-	else
-		/bin/true
-	fi
+	getent passwd steam > /dev/null 2>&1 && userdel steam
+	getent group steam > /dev/null 2>&1 && groupdel steam
 }
